server:
  port: 8080

spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE_NAME}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      host: ${MONGO_DATABASE_URL}
      port: 27017
      authentication-database: admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG